"""Utils package for the Rental Management System."""
from src.utils.date_helpers import (
    add_days,
    add_months,
    date_range_overlaps,
    days_between,
    get_current_date,
    get_current_datetime,
    is_overdue,
    months_between,
)
from src.utils.exceptions import (
    BusinessRuleViolationError,
    ContractNotActiveError,
    DuplicateBookingError,
    EntityAlreadyExistsError,
    EntityNotFoundError,
    InvalidStateTransitionError,
    InvoiceAlreadyPaidError,
    RentalSystemError,
    SpaceNotAvailableError,
    TenantBlockedError,
    ValidationError,
)
from src.utils.id_generator import generate_id, generate_prefixed_id
from src.utils.validators import (
    validate_date_range,
    validate_email,
    validate_non_empty_string,
    validate_non_negative_amount,
    validate_phone,
    validate_positive_amount,
)

__all__ = [
    "generate_id",
    "generate_prefixed_id",
    "validate_email",
    "validate_phone",
    "validate_date_range",
    "validate_positive_amount",
    "validate_non_negative_amount",
    "validate_non_empty_string",
    "months_between",
    "days_between",
    "add_months",
    "add_days",
    "is_overdue",
    "get_current_date",
    "get_current_datetime",
    "date_range_overlaps",
    "RentalSystemError",
    "EntityNotFoundError",
    "EntityAlreadyExistsError",
    "InvalidStateTransitionError",
    "ValidationError",
    "BusinessRuleViolationError",
    "TenantBlockedError",
    "SpaceNotAvailableError",
    "ContractNotActiveError",
    "InvoiceAlreadyPaidError",
    "DuplicateBookingError",
]
